name: zip
description: The premier solution for gameday travel needs modeled after the successes of Uber and Lyft.
version: 0.1.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

path_provider: 1.6.1

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^5.4.2
  cloud_firestore: ^0.14.3
  cloud_functions: ^0.6.0+1
  firebase_core: ^0.5.0+1
  firebase_auth: ^0.18.1+2
  firebase_analytics: ^6.0.2
  firebase_messaging: ^7.0.3
  flutter_local_notifications: ^2.0.0+1
  font_awesome_flutter: 8.10.0
  google_sign_in: ^4.4.0
  flutter_facebook_login: ^3.0.0
  shared_preferences: ^0.5.6+3
  flutter_swiper: ^1.1.6
  google_maps_flutter: ^0.5.11
  geolocator: ^5.3.1
  location: ^3.0.0
  location_permissions: ^2.0.4+1
  percent_indicator: ^2.1.1+1
  modal_progress_hud: ^0.1.2
  image_picker: 0.6.3+4
  firebase_storage: ^4.0.1
  flutter_polyline_points: ^0.1.0
  maps_launcher: ^1.2.0
  webview_flutter: ^0.3.19+9
  geoflutterfire: ^2.1.0
  stripe_payment: ^1.0.10
  stripe: 
  stripe_sdk: ^3.0.1+1
  http: ^0.12.0+4
  flutter_google_places: ^0.2.4
  google_maps_webservice: 
  email_launcher: ^1.0.0
  mailto: ^1.0.0
  strings: ^0.1.4
  flutter_email_sender: ^3.0.1
  keyboard_attachable: ^1.0.3
  unicorndial: "^1.1.5"
  material_design_icons_flutter: ^4.0.5855
  flutter_speed_dial: ^2.1.1
  geocoding: ^1.0.5
  polyline: ^1.0.0
  


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  
  flutter_auth_buttons:

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: any
  rxdart:
  flutter_automation: any
  flutter_launcher_icons: any

dependency_overrides:
  mockito: any
  flutter_test:
    sdk: flutter
  flutter_automation: any
  


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/iTunesArtwork@1x.png"



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/profile_default.png
    - assets/golf_cart.png
    - assets/Zip Yellow B.png
    - assets/iTunesArtwork@1x.png
    - assets/map_style.txt
    - assets/connectstripe_blurple_2x.png
    - assets/connectstripe_blurple_4x.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  # - assets/mountains.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf
    - family:  MyFlutterApp
      fonts:
        - asset: fonts/MyFlutterApp.ttf






